apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    app: load
spec:
  replicas: 50
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load
        image: gcr.io/[YourProjectID]/receiver:latest
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - containerPort: 8080
        env:
            - name: REDISPORT
              value: "6379"
            - name: REDISHOST
              value: "[YourRedisIP]"
            - name: SCALE_ENV
              value: "GKE"
            - name: ENDPOINT
              value: "[YourIngressIP]"
            - name: PORT
              value: "8080"          

